import { afterEach, beforeEach, expect, test } from "bun:test";
import { lstat, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { absent, failure } from "../helpers/failure.ts";
import { DEFAULT_KEYBINDS, runSetup, type SetupOptions, type SetupStep } from "../../src/commands/setup.ts";
import { SetupPathError } from "../../src/setup/paths.ts";

let root = "";
let env: Record<string, string>;

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), "pw-setup-cmd-"));
  env = { XDG_DATA_HOME: join(root, "data"), XDG_CONFIG_HOME: join(root, "config") };
});

afterEach(async () => {
  await rm(root, { recursive: true, force: true });
});

function options(step: SetupStep, extra: Partial<SetupOptions> = {}): SetupOptions {
  return { step, force: false, print: false, json: false, ...DEFAULT_KEYBINDS, ...extra };
}

const LINUX = { platform: "linux", cliVersion: "9.9.9" } as const;
const MACOS = { platform: "darwin", cliVersion: "9.9.9" } as const;

interface Envelope {
  cli_version: string;
  protocol: { minimum: number; maximum: number };
  ok: Record<string, unknown>;
}

async function json(step: SetupStep, extra: Partial<SetupOptions>, deps: typeof LINUX | typeof MACOS = LINUX): Promise<Envelope> {
  const { stdout } = await runSetup(options(step, { ...extra, json: true }), { env, ...deps });
  expect(stdout.endsWith("\n")).toBe(true);
  return JSON.parse(stdout) as Envelope;
}

test("setup scripts prints one line per installed script", async () => {
  const { stdout } = await runSetup(options("scripts"), { env, ...LINUX });
  const lines = stdout.trimEnd().split("\n");
  expect(lines).toHaveLength(5);
  expect(lines.every((line) => line.startsWith("installed script: "))).toBe(true);
  const again = await runSetup(options("scripts"), { env, ...LINUX });
  expect(again.stdout.split("\n")[0]).toStartWith("unchanged script: ");
});

test("setup scripts --json carries the envelope, the directory and per-file outcomes", async () => {
  const envelope = await json("scripts", {});
  expect(envelope.cli_version).toBe("9.9.9");
  expect(envelope.protocol).toEqual({ minimum: 1, maximum: 1 });
  expect(envelope.ok["step"]).toBe("scripts");
  expect(envelope.ok["dir"]).toBe(join(root, "data", "pohunek", "bin"));
  expect((envelope.ok["files"] as { outcome: string }[]).map((file) => file.outcome)).toEqual(["created", "created", "created", "created", "created"]);
});

test("setup config skips a differing file and says how to replace it", async () => {
  await runSetup(options("config"), { env, ...LINUX });
  await writeFile(join(root, "config", "pohunek", "launcher.conf"), "mine");
  const { stdout } = await runSetup(options("config"), { env, ...LINUX });
  expect(stdout).toContain("skipped (exists, differs; use --force to replace): ");
  expect(stdout).toContain("unchanged: ");
  const forced = await runSetup(options("config", { force: true }), { env, ...LINUX });
  expect(forced.stdout).toContain("overwritten: ");
  expect(await readFile(join(root, "config", "pohunek", "launcher.conf"), "utf8")).toContain("host=local");
});

test("setup sway writes the drop-in and reminds about the include", async () => {
  const { stdout } = await runSetup(options("sway"), { env, ...LINUX });
  expect(stdout).toContain("wrote sway drop-in: ");
  expect(stdout).toContain(`NOTE: add \`include ${join(root, "config", "sway")}/config.d/*\``);
});

test("setup sway --print outputs the snippet only and writes nothing", async () => {
  const { stdout } = await runSetup(options("sway", { print: true, keybind: "$mod+q" }), { env, ...LINUX });
  expect(stdout).toStartWith("# pohunek - generated by");
  expect(stdout).toContain("bindsym $mod+q exec $pohunek_launcher");
  expect(await absent(lstat(join(root, "config")))).toBe(true);
});

test("setup sway --print --json keeps stdout a single JSON document with the snippet inside", async () => {
  const envelope = await json("sway", { print: true });
  expect(envelope.ok["printed"]).toBe(true);
  expect(envelope.ok["snippet"]).toContain("bindsym $mod+p exec $pohunek_launcher");
  expect(envelope.ok["outcome"]).toBeNull();
});

test("the full setup on linux installs scripts, config and the drop-in and lists next steps", async () => {
  const envelope = await json("all", {});
  expect(Object.keys(envelope.ok).sort()).toEqual(["config", "next_steps", "scripts", "skipped", "step", "sway"]);
  expect(envelope.ok["skipped"]).toEqual([]);
  expect((envelope.ok["next_steps"] as string[]).length).toBeGreaterThan(0);

  const human = await runSetup(options("all"), { env, ...LINUX });
  expect(human.stdout).toContain("unchanged script: ");
  expect(human.stdout).toContain("\nNext steps:\n  1. ");
  expect(human.stdout).not.toContain("skipped ");
});

test("the full setup on macOS writes only the config and reports scripts and sway as skipped", async () => {
  const envelope = await json("all", {}, MACOS);
  expect(envelope.ok["scripts"]).toBeUndefined();
  expect(envelope.ok["sway"]).toBeUndefined();
  expect((envelope.ok["skipped"] as { step: string }[]).map((entry) => entry.step)).toEqual(["scripts", "sway"]);
  expect(await absent(lstat(join(root, "data")))).toBe(true);
  expect(await absent(lstat(join(root, "config", "sway")))).toBe(true);
  expect((await lstat(join(root, "config", "pohunek", "launcher.conf"))).isFile()).toBe(true);

  const human = await runSetup(options("all"), { env, ...MACOS });
  expect(human.stdout).toContain("skipped sway: ");
  expect(human.stdout).toContain("skipped scripts: ");
  expect(human.stdout).not.toContain("include");
});

test("an explicit setup sway on macOS succeeds without writing", async () => {
  const envelope = await json("sway", {}, MACOS);
  expect(envelope.ok).toMatchObject({ step: "sway", skipped: true });
  expect((await runSetup(options("sway"), { env, ...MACOS })).stdout).toStartWith("skipped sway: ");
  expect(await absent(lstat(join(root, "config")))).toBe(true);
});

test("an explicit setup scripts on macOS installs anyway", async () => {
  const { stdout } = await runSetup(options("scripts"), { env, ...MACOS });
  expect(stdout).toContain("installed script: ");
});

test("an environment without XDG variables and HOME is a SetupPathError before anything is written", async () => {
  expect(await failure(runSetup(options("all"), { env: {}, ...LINUX }))).toBeInstanceOf(SetupPathError);
});
