import { expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { CONFIG_ASSETS, renderSwayDropin, SCRIPT_ASSETS } from "../../src/setup/assets.ts";

const LAUNCHERS = new URL("../../../launchers/", import.meta.url);

async function source(name: string): Promise<string> {
  return readFile(new URL(name, LAUNCHERS), "utf8");
}

test("embedded scripts are byte-identical to the files under launchers/", async () => {
  expect(SCRIPT_ASSETS.map((asset) => asset.name).sort()).toEqual(
    ["lib.sh", "pohunek-launch-issue", "pohunek-launch-pr", "pohunek-rofi", "pohunek-rofi-issue"],
  );
  for (const asset of SCRIPT_ASSETS) {
    expect(asset.body).toBe(await source(asset.name));
  }
});

test("every embedded script is a shell script with a shebang", () => {
  for (const asset of SCRIPT_ASSETS) {
    expect(asset.body.startsWith("#!/bin/sh\n")).toBe(true);
  }
});

test("config assets are byte-identical to the templates under launchers/templates", async () => {
  for (const asset of CONFIG_ASSETS) {
    expect(asset.body).toBe(await source(`templates/${asset.name}`));
  }
  expect(CONFIG_ASSETS.map((asset) => asset.name)).toEqual([
    "launcher.conf",
    "prompts/issue.tmpl",
    "prompts/pr.tmpl",
    "prompts/review.tmpl",
  ]);
});

function templateVariables(template: string): string[] {
  return [...template.matchAll(/\$\{([^}]*)\}/g)].map((match) => match[1] ?? "");
}

function asset(name: string): string {
  const found = CONFIG_ASSETS.find((candidate) => candidate.name === name);
  if (found === undefined) throw new Error(`missing asset ${name}`);
  return found.body;
}

// The pohunek prompt renderer rejects any variable outside the provider context.
test("issue and pr templates reference only provider variables", () => {
  const known = ["provider", "id", "number", "title", "body", "branch", "url"];
  for (const name of ["prompts/issue.tmpl", "prompts/pr.tmpl"]) {
    for (const variable of templateVariables(asset(name))) {
      expect(known).toContain(variable);
    }
  }
});

test("the review template references only review variables", () => {
  const known = ["provider", "branch", "source", "comments", "comment_count"];
  const used = templateVariables(asset("prompts/review.tmpl"));
  expect(used.length).toBeGreaterThan(0);
  for (const variable of used) {
    expect(known).toContain(variable);
  }
});

test("launcher.conf carries host-level keys only", () => {
  const conf = asset("launcher.conf");
  // attach_reconnect_* belong to core's attach.conf, which `pohunek attach` reads.
  for (const removed of [
    "project=",
    "agent=",
    "issue_action",
    "pr_action",
    "banner=",
    "banner_interval_seconds",
    "attach_reconnect",
  ]) {
    expect(conf).not.toContain(removed);
  }
  for (const key of ["host=local", "terminal=", "linear_cli=linear", "mark_retry_count=20"]) {
    expect(conf).toContain(key);
  }
});

const VALUES = { launcher: "'/d/bin/pohunek-rofi'", keybind: "$mod+x" };

test("the sway drop-in binds the switcher and keeps sway variables intact", () => {
  expect(renderSwayDropin(VALUES)).toBe(
    [
      "# pohunek - generated by `pohunek-work setup sway`. Edit launcher.conf, not this file.",
      "bindsym $mod+x exec exec '/d/bin/pohunek-rofi'",
      "",
    ].join("\n"),
  );
});

test("the issue picker binding is added after the switcher binding when requested", () => {
  expect(renderSwayDropin({ ...VALUES, issue: { keybind: "$mod+y", launcher: "'/d/bin/pohunek-rofi-issue'", project: "'ui'" } })).toBe(
    [
      "# pohunek - generated by `pohunek-work setup sway`. Edit launcher.conf, not this file.",
      "bindsym $mod+x exec exec '/d/bin/pohunek-rofi'",
      "bindsym $mod+y exec exec '/d/bin/pohunek-rofi-issue' 'ui'",
      "",
    ].join("\n"),
  );
});

test("a value is not expanded a second time", () => {
  expect(renderSwayDropin({ ...VALUES, launcher: "{{keybind}}" })).toContain("exec exec {{keybind}}\n");
});
