import { expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { CONFIG_ASSETS, renderSwayDropin, SCRIPT_ASSETS } from "../../src/setup/assets.ts";

const LAUNCHERS = new URL("../../../launchers/", import.meta.url);

async function source(name: string): Promise<string> {
  return readFile(new URL(name, LAUNCHERS), "utf8");
}

test("embedded scripts are byte-identical to the files under launchers/", async () => {
  expect(SCRIPT_ASSETS.map((asset) => asset.name).sort()).toEqual(
    ["lib.sh", "pohunek-launch-issue", "pohunek-launch-pr", "pohunek-rofi", "pohunek-rofi-issue"],
  );
  for (const asset of SCRIPT_ASSETS) {
    expect(asset.body).toBe(await source(asset.name));
  }
});

test("every embedded script is a shell script with a shebang", () => {
  for (const asset of SCRIPT_ASSETS) {
    expect(asset.body.startsWith("#!/bin/sh\n")).toBe(true);
  }
});

test("config assets are byte-identical to the templates under launchers/templates", async () => {
  for (const asset of CONFIG_ASSETS) {
    expect(asset.body).toBe(await source(`templates/${asset.name}`));
  }
  expect(CONFIG_ASSETS.map((asset) => asset.name)).toEqual([
    "launcher.conf",
    "prompts/issue.tmpl",
    "prompts/pr.tmpl",
    "prompts/review.tmpl",
  ]);
});

function templateVariables(template: string): string[] {
  return [...template.matchAll(/\$\{([^}]*)\}/g)].map((match) => match[1] ?? "");
}

function asset(name: string): string {
  const found = CONFIG_ASSETS.find((candidate) => candidate.name === name);
  if (found === undefined) throw new Error(`missing asset ${name}`);
  return found.body;
}

// The pohunek prompt renderer rejects any variable outside the provider context.
test("issue and pr templates reference only provider variables", () => {
  const known = ["provider", "id", "number", "title", "body", "branch", "url"];
  for (const name of ["prompts/issue.tmpl", "prompts/pr.tmpl"]) {
    for (const variable of templateVariables(asset(name))) {
      expect(known).toContain(variable);
    }
  }
});

test("the review template references only review variables", () => {
  const known = ["provider", "branch", "source", "comments", "comment_count"];
  const used = templateVariables(asset("prompts/review.tmpl"));
  expect(used.length).toBeGreaterThan(0);
  for (const variable of used) {
    expect(known).toContain(variable);
  }
});

test("launcher.conf carries host-level keys only", () => {
  const conf = asset("launcher.conf");
  for (const removed of ["project=", "agent=", "issue_action", "pr_action", "banner=", "banner_interval_seconds"]) {
    expect(conf).not.toContain(removed);
  }
  for (const key of ["host=local", "terminal=", "linear_cli=linear", "attach_reconnect_max_attempts=3"]) {
    expect(conf).toContain(key);
  }
});

const VALUES = {
  launcher: "/d/bin/pohunek-rofi",
  issue_launcher: "/d/bin/pohunek-rofi-issue",
  keybind: "$mod+x",
  issue_keybind: "$mod+y",
};

test("the sway drop-in binds both launchers and keeps sway variables intact", () => {
  expect(renderSwayDropin(VALUES)).toBe(
    [
      "# pohunek - generated by `pohunek-work setup sway`. Edit launcher.conf, not this file.",
      "set $pohunek_launcher /d/bin/pohunek-rofi",
      "bindsym $mod+x exec $pohunek_launcher",
      "set $pohunek_issue_launcher /d/bin/pohunek-rofi-issue",
      "bindsym $mod+y exec $pohunek_issue_launcher",
      "",
    ].join("\n"),
  );
});

test("a placeholder without a value is an error and values are not expanded twice", () => {
  expect(() => renderSwayDropin(VALUES, "{{launcher}} {{missing}}")).toThrow("unknown variable: missing");
  expect(renderSwayDropin({ ...VALUES, launcher: "{{keybind}}" }, "{{launcher}}")).toBe("{{keybind}}");
});
